package core

var DefaultProxies = []string{
	"gh-proxy.com",
	"ghproxy.net",
	"git.yylx.win",
	"gh.927223.xyz",
	"gh.felicity.ac.cn",
	"tvv.tw",
	"jiashu.1win.eu.org",
	"gh.inkchills.cn",
	"gh.my-website.ccwu.cc",
	"gh.07150721.xyz",
	"cfgh.ikgy.top",
	"xsadwsd.kdns.fr",
	"ghproxy.felicity.land",
	"gh-proxy.org",
	"v4.gh-proxy.org",
	"v6.gh-proxy.org",
	"cdn.gh-proxy.org",
	"edgeone.gh-proxy.org",
	"hk.gh-proxy.org",
	"gh-proxy.cn",
	"gitproxy.mrhjx.cn",
	"gh.sixyin.com",
	"gh.monlor.com",
	"ghfast.top",
	"gh.jasonzeng.dev",
	"gp.zkitefly.eu.org",
	"ghproxy.monkeyray.net",
	"gh.noki.icu",
	"g.blfrp.cn",
}
