// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecords() {
  return window['go']['bindings']['ConfigAPI']['ClearRecords']();
}

export function ExportRecords() {
  return window['go']['bindings']['ConfigAPI']['ExportRecords']();
}

export function GetSettings() {
  return window['go']['bindings']['ConfigAPI']['GetSettings']();
}

export function PickDirectory() {
  return window['go']['bindings']['ConfigAPI']['PickDirectory']();
}

export function ResetSettings() {
  return window['go']['bindings']['ConfigAPI']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveSettings'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['bindings']['ConfigAPI']['SetCtx'](arg1);
}
