// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function ClearRecords():Promise<void>;

export function ExportRecords():Promise<string>;

export function GetSettings():Promise<bindings.Settings>;

export function PickDirectory():Promise<string>;

export function ResetSettings():Promise<bindings.Settings>;

export function SaveSettings(arg1:bindings.Settings):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
