// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['bindings']['DownloadAPI']['CreateTask'](arg1);
}

export function DeleteProxies(arg1) {
  return window['go']['bindings']['DownloadAPI']['DeleteProxies'](arg1);
}

export function GetSuccessRecords() {
  return window['go']['bindings']['DownloadAPI']['GetSuccessRecords']();
}

export function GetTasks() {
  return window['go']['bindings']['DownloadAPI']['GetTasks']();
}

export function SetCtx(arg1) {
  return window['go']['bindings']['DownloadAPI']['SetCtx'](arg1);
}
