// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function CreateTask(arg1:bindings.CreateTaskReq):Promise<bindings.TaskInfo>;

export function DeleteProxies(arg1:Array<string>):Promise<void>;

export function GetSuccessRecords():Promise<Array<bindings.ProxyRecord>>;

export function GetTasks():Promise<Array<bindings.TaskInfo>>;

export function SetCtx(arg1:context.Context):Promise<void>;
