// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['bindings']['DownloadAPI']['CancelTask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['bindings']['DownloadAPI']['CreateTask'](arg1);
}

export function DeleteProxies(arg1) {
  return window['go']['bindings']['DownloadAPI']['DeleteProxies'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['bindings']['DownloadAPI']['DeleteTask'](arg1);
}

export function GetSuccessRecords() {
  return window['go']['bindings']['DownloadAPI']['GetSuccessRecords']();
}

export function GetTasks() {
  return window['go']['bindings']['DownloadAPI']['GetTasks']();
}

export function RecordProxyFailure(arg1) {
  return window['go']['bindings']['DownloadAPI']['RecordProxyFailure'](arg1);
}

export function RecordProxySuccess(arg1, arg2, arg3) {
  return window['go']['bindings']['DownloadAPI']['RecordProxySuccess'](arg1, arg2, arg3);
}

export function SetCtx(arg1) {
  return window['go']['bindings']['DownloadAPI']['SetCtx'](arg1);
}
