// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function ExportProxies(arg1:string):Promise<void>;

export function GetProxies():Promise<Array<bindings.ProxyItem>>;

export function GetSilentProxies():Promise<Array<string>>;

export function ImportProxies(arg1:string):Promise<number>;

export function PreflightCheck():Promise<bindings.PreflightResult>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function TestAllProxies():Promise<void>;

export function TestProxy(arg1:string):Promise<bindings.ProxyTestResult>;

export function ToggleProxy(arg1:string,arg2:boolean):Promise<void>;

export function UnsilenceProxy(arg1:string):Promise<void>;
