// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportProxies(arg1) {
  return window['go']['bindings']['ProxyAPI']['ExportProxies'](arg1);
}

export function GetProxies() {
  return window['go']['bindings']['ProxyAPI']['GetProxies']();
}

export function GetSilentProxies() {
  return window['go']['bindings']['ProxyAPI']['GetSilentProxies']();
}

export function ImportProxies(arg1) {
  return window['go']['bindings']['ProxyAPI']['ImportProxies'](arg1);
}

export function PreflightCheck() {
  return window['go']['bindings']['ProxyAPI']['PreflightCheck']();
}

export function SetCtx(arg1) {
  return window['go']['bindings']['ProxyAPI']['SetCtx'](arg1);
}

export function TestAllProxies() {
  return window['go']['bindings']['ProxyAPI']['TestAllProxies']();
}

export function TestProxy(arg1) {
  return window['go']['bindings']['ProxyAPI']['TestProxy'](arg1);
}

export function ToggleProxy(arg1, arg2) {
  return window['go']['bindings']['ProxyAPI']['ToggleProxy'](arg1, arg2);
}

export function UnsilenceProxy(arg1) {
  return window['go']['bindings']['ProxyAPI']['UnsilenceProxy'](arg1);
}
