// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddress():Promise<string>;

export function IsRunning():Promise<boolean>;

export function Start(arg1:number,arg2:boolean):Promise<void>;

export function Stop():Promise<void>;
