// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddress() {
  return window['go']['bindings']['ServerAPI']['GetAddress']();
}

export function IsRunning() {
  return window['go']['bindings']['ServerAPI']['IsRunning']();
}

export function Start(arg1, arg2) {
  return window['go']['bindings']['ServerAPI']['Start'](arg1, arg2);
}

export function Stop() {
  return window['go']['bindings']['ServerAPI']['Stop']();
}
